### PR TITLE
Remove unused argument `candidate`

### PR DESCRIPTION
**Pull request by gasull**
Backport of https://github.com/Electron-Cash/Electron-Cash/pull/2215.

Related bug in Electron Cash: https://github.com/Electron-Cash/Electron-Cash/issues/2213

---
This change is [Reviewable](https://reviewable.io/reviews/bitcoin-abc/electrumabc/102)

### CODE REVIEW

**Comment by PiRK** [comment]
This method penalty_func on line 102 seems to be a dummy implementation that is not actually used anywhere. It is probably meant to document how the inheritor should implement the method. I think the solution would be to actually document the method in the base class with a docstring, and not implement it.

Something like that , for instance :

```
diff --git a/electroncash/coinchooser.py b/electroncash/coinchooser.py
index eff6f24a6..51df57275 100644
--- a/electroncash/coinchooser.py
+++ b/electroncash/coinchooser.py
@@ -25,6 +25,7 @@
 # SOFTWARE.
 from collections import defaultdict, namedtuple
 from math import floor, log10
+from typing import Callable, List, Dict

 from .bitcoin import sha256, COIN, TYPE_ADDRESS
 from .transaction import Transaction
@@ -100,10 +101,19 @@ class CoinChooserBase(PrintError):

         return list(map(make_Bucket, buckets.keys(), buckets.values()))

-    def penalty_func(self, tx):
-        def penalty(candidate):
-            return 0
-        return penalty
+    def penalty_func(self, tx: Transaction) -> Callable[[List[Dict]], int]:
+        """Return a penalty function that return a score for a given bucket
+        of coins.
+
+        The bucket is a list of UTXOs, each UTXO is a dict containing the
+        usual coin information (tx hash, value, index of the utxo in the
+        transaction's list of outputs...)
+
+        The score returned by the penalty function is used to sort the
+        candidate buckets when making a new transaction. The lower the score,
+        the more likely a list of UTXO will be chosen as inputs for the
+        transaction."""
+        raise NotImplementedError("to be implemented in subclass")

     def change_amounts(self, tx, count, fee_estimator, dust_threshold):
         # Break change up if bigger than max_change

```

**Comment by gasull** [comment]
> This method penalty_func on line 102 seems to be a dummy implementation that is not actually used anywhere.

It seems to be used, unless those calls are dead code too.

```
$ rg penalty_func
electroncash/coinchooser.py
103:    def penalty_func(self, tx):
197:                                      self.penalty_func(tx))
214:    def choose_buckets(self, buckets, sufficient_funds, penalty_func):
284:    def choose_buckets(self, buckets, sufficient_funds, penalty_func):
286:        penalties = [penalty_func(cand) for cand in candidates]
305:    def penalty_func(self, tx):
```

`vulture` doesn't report `penalty_func` as dead code.

**Comment by PiRK** [comment]
At the end, we only use the child class `CoinChooserPrivacy` which completely reimplements `penalty_func` without ever calling the base class implementation.

So when we  call `CoinChooserPrivacy.make_tx`, it uses `CoinChooserBase.make_tx` because that method is never overloaded, but when this mtehod calls `self.choose_buckets` or `self.penalty_func`, the overloaded methods are used.

**Comment by PiRK** [comment]
Design by inheritance is somewhat controversial nowadays: https://codeburst.io/inheritance-is-evil-stop-using-it-6c4f1caf5117

**Comment by gasull** [comment]
> At the end, we only use the child class `CoinChooserPrivacy` which completely reimplements `penalty_func` without ever calling the base class implementation.

I see.

I wonder what is the reason for having both `CoinChooserRandom` and `CoinChooserPrivacy`.  Is the idea to let the user opt for the kind of coin chooser they want, even if this isn't implemented yet?

I cannot think of a good reason why someone would prefer something other than `CoinChooserPrivacy`.

> Design by inheritance is somewhat controversial nowadays

I agree.  

You can accomplish the same inheriting only from abstract classes and never overriding a non-abstract method, but you cannot enforce others will do this.  So it risks becoming spaghetti code very quickly.

Maybe the `CoinChooser*` classes could be refactored into an abstract class and a non-abstract class, and then refactor this again using composition instead of inheritance.

But right now I don't even see why we need anything more than a single `CoinChooserPrivacy` class.  Do we?

**Comment by PiRK** [comment]
CoinchooserPrivacy inherits CoinchooserRandom. I guess at some point the intention must have been to provide multiple coinchoosers and let the user select his favorite one. I can see some situations in which you might want to consolidate lots of small utxos, or do the opposite.

**Comment by gasull** [comment]
Should we refactor these `CoinChooser*` classes with this?:

 - Removing `penalty_func` from `CoinChooserBase`.
 - `CoinChooserPrivacy` inheriting directly from abstract `CoinChooserBase`.
 - Moving any methods common to `ConChooserRandom` and `CoinChooserPrivacy` to `CoinChooserBase`.

**Comment by PiRK** [comment]
From what I can see, there are already no common methodes between ConChooserRandom and CoinChooserPrivacy. The only duplicated methods seem to be the clumsy abstract methods in CoinChooserBase: `keys`, `penalty_func` and `choose_buckets`. I would just make sure that the abstract methods clearly show that they need to be implemented, with a `raise NotImplementedError`, and that they are properly documented instead of using the dummy code.

**Comment by gasull** [comment]
> The only duplicated methods seem to be the clumsy abstract methods in CoinChooserBase: `keys`, `penalty_func` and `choose_buckets`. I would just make sure that the abstract methods clearly show that they need to be implemented

Done.  I did a small refactoring moving the implementation of `penalty_func` out of the base class, and used the `abc` module to enforce that the abstract class and methods aren't used.

**Comment by PiRK** [comment]
I still think that removing `candidate` makes the code worse. Because the only use for this unused  code path is to document how a real `penalty_func` should be implemented.  A real penalty function needs to accept a parameter (see how it is called in `CoinChooserRandom.choose_buckets`).
Removing the dead code path altogether and adding a basic documentation to the `@abstractmethod` would be preferable.

**Pull request closed without merging**
