### PR TITLE
Update currencies.json

### PR DESCRIPTION
**Pull request by privatebusiness88**

### CODE REVIEW

**Comment by PiRK** [comment]
Is this some kind of a test?

**Comment by privatebusiness88** [comment]
Hello,

Would you mind give me more details ?

With my humble regards
Kevin wijaya

Dikirim dari Outlook untuk Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by PiRK** [comment]
I do not understand this pull request.

**Comment by privatebusiness88** [comment]
Hello,

Thank you for your reply.
According to new coin, needed to be add up to currencies as coin name to have an value for.

And would you mind help me check if ***@***.*** are still active and being invalid alias in server.

Thank you.

With my humble regards,
Kevin wijaya

Dikirim dari Outlook untuk Android<https://aka.ms/AAb9ysg>
________________________________

**Pull request closed without merging**
